DataRawLib = {}

DataRawLib.cat_sigs = require("lib.cat-sigs")
DataRawLib.categories = require("lib.categories")
DataRawLib.duplicate = require("lib.duplicate")
DataRawLib.extract = require("lib.extract")
DataRawLib.key = require("lib.key")
DataRawLib.locale = require("lib.locale")
DataRawLib.map_gen = require("lib.map-gen")
DataRawLib.mtm = require("lib.mtm")
DataRawLib.patching = require("lib.patching")
DataRawLib.pipe_conns = require("lib.pipe-conns")
DataRawLib.resize = require("lib.resize")
DataRawLib.room = require("lib.room")
DataRawLib.traversal = require("lib.traversal")
DataRawLib.trigger = require("lib.trigger")